/*
comentário em 
múltiplas linhas
*/

--comentários

--CTRL+S - SALVA DOCTO
--CTRL+K, CTRL+X - INSERT SNIPPET
--CTRL+K, CTRL+S - SURROUND WITH
--SHIFT+ALT+ENTER - FULL SCREEN
--CTRL+SHIFT+U - MAIÚSCULAS
--CTRL+SHIFT+L - MINÚSCULAS

SELECT GETDATE() --FUNÇÃO

--F5 - EXECUTA O COMANDO SELECIONADO
--CTRL+F5 - FAZ O PARSE DO COMANDO SELECIONADO

--PROCE -> PARSE, RESOLVE, OPTIMIZE, CACHE, EXECUTE
--   CE ->                           CACHE, EXECUTE

EXEC dbo.sp_help --PROCEDURE

SELECT @@VERSION --FUNÇÃO -> VARIÁVEL DE AMBIENTE

--CTRL+T - TEXT
--CTRL+D - DATA

SELECT @@VERSION 

--CTRL+R - RESULT PANEL
--CTRL+UP - DESCE TEXTO
--CTRL+_DOWN - SOBE TEXTO

USE MASTER

IF EXISTS(SELECT * FROM SYS.databases WHERE name = 'DB')
BEGIN
	ALTER DATABASE DB
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB
END

CREATE DATABASE DB
GO

USE DB

CREATE TABLE dbo.PESSOA
(
	COD_PESSOA INT, 
	NOME_PESSOA VARCHAR(50)
)
--OU
--CREATE TABLE dbo.Pessoa
--(
--	PessoaId INT, 
--	PessoaNome VARCHAR(50)
--)

--CTRL+K, CTRL+C - COMENTA O CÓDIGO
--CTRL+K, CTRL+U - REMOVE COMENTÁRIO DO CÓDIGO

INSERT /*INTO*/ dbo.PESSOA
VALUES (1, 'ADÃO'), 
	(2, 'EVA'), 
	(3, 'CAIM'), 
	(4, 'ABEL')

SELECT *
FROM dbo.PESSOA

EXEC SP_HELPSORT --LATIN1_GENERAL_CI_AS

SELECT *
FROM ::FN_HELPCOLLATIONS()

EXEC SYS.sp_help 

EXEC SYS.sp_help PESSOA

EXEC SYS.sp_msforeachtable 'PRINT ''?'''

EXEC SYS.sp_msforeachtable 'DROP TABLE ?'

--F1 - HELP DO COMANDO SELECIONADO

SELECT * 
FROM master.dbo.spt_monitor
