USE master

IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'DB')
BEGIN
	ALTER DATABASE DB
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB
END

CREATE DATABASE DB
GO

USE DB

CREATE TABLE OUTROS
(
	GUID UNIQUEIDENTIFIER, 
	VARBINARY VARBINARY(100), 
	BINARY BINARY(100), 
	VARBINARYMAX VARBINARY(MAX), 
	IMAGE IMAGE 	 
)

INSERT OUTROS
VALUES 
(
	NEWID(), 
	PWDENCRYPT('ABC'), 
	PWDENCRYPT('ABC'), 
	PWDENCRYPT('ABC'), 
	PWDENCRYPT('ABC')	
)

SELECT *
FROM OUTROS

SELECT PWDENCRYPT('AGNALDO') --CALCULA O HASH DO DADO PASSADO
SELECT PWDENCRYPT('AGNALDO')
SELECT PWDENCRYPT('AGNALDO')

SELECT NEWID()
SELECT NEWID()

SELECT PWDCOMPARE('agnaldo', PWDENCRYPT('AGNALDO')) 

SELECT * 
FROM OUTROS

SELECT VARBINARY, 
	PWDCOMPARE('123', VARBINARY)
FROM OUTROS

SELECT VARBINARY, 
	PWDCOMPARE('ABC', VARBINARY)
FROM OUTROS

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY, 
	NOME_PRODUTO VARCHAR(50)
)

INSERT PRODUTO 
VALUES ('MARTELO'), 
	('MARRETA'), 
	('SERROTE')

ALTER TABLE PRODUTO
ADD PRECO_PRODUTO DEC(9,2)

UPDATE PRODUTO
SET PRECO_PRODUTO = CASE COD_PRODUTO 
						WHEN 1 THEN 10 
						WHEN 2 THEN 20
						WHEN 3 THEN 10.5
					END

SELECT *
FROM PRODUTO

SELECT COUNT(*)
FROM PRODUTO

SELECT MIN(PRECO_PRODUTO), 
	MAX(PRECO_PRODUTO), 
	AVG(PRECO_PRODUTO), 
	SUM(PRECO_PRODUTO)
FROM PRODUTO

DROP TABLE PRODUTO

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY,
	NOME_PRODUTO VARCHAR(50),
	TIPO_PRODUTO VARCHAR(50),
	PRECO_PRODUTO MONEY
)

INSERT PRODUTO
VALUES ('MARTELO','FERRAMENTA',10), 
	('SERROTE','FERRAMENTA',20), 
	('AÇÚCAR','ALIMENTO',2), 
	('SAL','ALIMENTO',1.5), 
	('MARRETA','FERRAMENTA',30)

SELECT *
FROM PRODUTO

SELECT TIPO_PRODUTO, 
	COUNT(*) AS 'QTD', 
	MIN(PRECO_PRODUTO) AS 'MIN', 
	MAX(PRECO_PRODUTO) AS 'MAX', 
	AVG(PRECO_PRODUTO) AS 'AVG', 
	SUM(PRECO_PRODUTO) AS 'SUM'
FROM PRODUTO
GROUP BY TIPO_PRODUTO

SELECT *
FROM PRODUTO

INSERT PRODUTO
VALUES ('PIMENTA', 'ALIMENTO', NULL)

SELECT MIN(PRECO_PRODUTO) AS 'MIN', 
	MAX(PRECO_PRODUTO) AS 'MAX', 
	AVG(PRECO_PRODUTO) AS 'AVG', 
	AVG(ISNULL(PRECO_PRODUTO, 0)) AS 'AVG(ISNULL)', 
	SUM(PRECO_PRODUTO) AS 'SUM', 
	COUNT(PRECO_PRODUTO) AS 'COUNT(PRECO_PRODUTO)', 
	COUNT(*) AS 'COUNT(*)'
FROM PRODUTO 
WHERE TIPO_PRODUTO = 'ALIMENTO'

SELECT TIPO_PRODUTO, 
	MIN(PRECO_PRODUTO) AS 'MIN', 
	MAX(PRECO_PRODUTO) AS 'MAX', 
	AVG(PRECO_PRODUTO) AS 'AVG', 
	AVG(ISNULL(PRECO_PRODUTO, 0)) AS 'AVG(ISNULL)', 
	SUM(PRECO_PRODUTO) AS 'SUM', 
	COUNT(PRECO_PRODUTO) AS 'COUNT(PRECO_PRODUTO)', 
	COUNT(*) AS 'COUNT(*)'
FROM PRODUTO 
GROUP BY TIPO_PRODUTO

SELECT CAST('123' AS INT)
SELECT CONVERT(INT, '123')

SELECT CAST('BATATINHA' AS INT)
SELECT CONVERT(INT, 'BATATINHA')

SELECT CAST(GETDATE() AS VARCHAR), 
	CONVERT(VARCHAR, GETDATE()), 
	CONVERT(VARCHAR, GETDATE(), 103), 
	CONVERT(VARCHAR, GETDATE(), 108)

SELECT ISNUMERIC('123'), 
	ISNUMERIC('1234.45'), 
	ISNUMERIC('BATATINHA'), 
	ISNUMERIC('1E2') -- 1 X 10 ^ 2

DECLARE @X VARCHAR(10) = '123' --'AB'

IF ISNUMERIC(@X) = 1
BEGIN 
	DECLARE @Y INT = CONVERT(INT, @X)

	SELECT @X, @Y, CONVERT(INT, 0x100)
END

SELECT CONVERT(FLOAT, '1.2E+2')

SELECT CONVERT(FLOAT, '1.2E-2')

SELECT 2E0, 2E, 2E1, 2E2, 2E3

SELECT *, 
	ISNULL(PRECO_PRODUTO, 0) AS 'ISNULL', 
	COALESCE(PRECO_PRODUTO, 0) AS 'COALESCE'
FROM PRODUTO

CREATE TABLE TABELA
(
	CAMPO1 INT, 
	CAMPO2 INT
)

INSERT TABELA
VALUES (1,1), 
	(1,2),
	(NULL,1),
	(1,NULL), 
	(NULL, NULL)

SELECT *, 
	NULLIF(CAMPO1, CAMPO2)
FROM TABELA

