USE DB

SELECT COUNT(*), 
	COUNT(PRECO_PRODUTO),  
	COUNT(DISTINCT TIPO_PRODUTO)
FROM PRODUTO

--CLIENTE, UF, CIDADE, PEDIDO, ITEM_PEDIDO, PRODUTO
CREATE TABLE PEDIDO
(
	COD_CLIENTE INT, 
	NOME_CLIENTE VARCHAR(50), 
	CIDADE_CLIENTE VARCHAR(50), 
	ESTADO_CLIENTE CHAR(2), 
	VALOR_PEDIDO DEC(9,2)
)

INSERT PEDIDO 
VALUES (1, 'ADÃO', 'SPO', 'SP', 1000), 
	(2, 'ADÃO', 'LORENA', 'SP', 100), 
	(3, 'EVA', 'SPO', 'SP', 50), 
	(1, 'ADÃO', 'SPO', 'SP', 1000), 
	(4, 'TIÃO', 'PA', 'MG', 10), 
	(3, 'EVA', 'SPO', 'SP', 1000), 
	(5, 'CHICO', 'BHZ', 'MG', 10), 
	(2, 'ADÃO', 'LORENA', 'SP', 1000)

SELECT SUM(VALOR_PEDIDO) AS 'TOTAL'
FROM PEDIDO

SELECT ESTADO_CLIENTE, 
	SUM(VALOR_PEDIDO) AS 'TOTAL'
FROM PEDIDO
GROUP BY ESTADO_CLIENTE

SELECT ESTADO_CLIENTE, 
	CIDADE_CLIENTE, 
	SUM(VALOR_PEDIDO) AS 'TOTAL'
FROM PEDIDO
GROUP BY ESTADO_CLIENTE, 
	CIDADE_CLIENTE

SELECT ESTADO_CLIENTE, 
	CIDADE_CLIENTE, 
	NOME_CLIENTE, 
	COUNT(*) AS 'QTD', 
	SUM(VALOR_PEDIDO) AS 'TOTAL'
FROM PEDIDO
GROUP BY ESTADO_CLIENTE, 
	CIDADE_CLIENTE, 
	NOME_CLIENTE

SELECT ESTADO_CLIENTE, 
	CIDADE_CLIENTE, 
	NOME_CLIENTE, 
	SUM(VALOR_PEDIDO) AS 'TOTAL'
FROM PEDIDO
GROUP BY ESTADO_CLIENTE, 
	CIDADE_CLIENTE, 
	NOME_CLIENTE
HAVING SUM(VALOR_PEDIDO) BETWEEN 1000 AND 2000
ORDER BY TOTAL
